import turtle

saqib = turtle.Turtle()

# saqib.forward(100)
# saqib.left(45)
# saqib.forward(100)
# saqib.right(90)
# saqib.fd(100)

# saqib.color("blue")
# saqib.begin_fill()
# saqib.forward(100)
# saqib.left(90)
# saqib.color("orange")
# saqib.forward(100)
# saqib.left(90)
# saqib.color("purple")
# saqib.forward(100)
# saqib.left(90)
# saqib.color("black", "cyan")
# saqib.forward(100)
# saqib.end_fill()


# saqib.color("blue")
# saqib.forward(100)
# saqib.left(90)
# saqib.color("orange")
# saqib.forward(100)
# saqib.left(90)
# saqib.color("purple")
# saqib.forward(100)
# saqib.left(90)
# saqib.color("black")
# saqib.forward(100)
# saqib.color("cyan")
# saqib.forward(100)
saqib.color("blue", "cyan")

saqib.begin_fill()
saqib.forward(100)
saqib.left(90)
saqib.forward(100)
saqib.left(90)
saqib.forward(100)
saqib.left(90)
saqib.forward(100)
saqib.end_fill()

saqib.penup()
saqib.forward(50)
saqib.pendown()

saqib.begin_fill()
saqib.forward(100)
saqib.left(90)
saqib.forward(100)
saqib.left(90)
saqib.forward(100)
saqib.left(90)
saqib.forward(100)
saqib.end_fill()

turtle.done()